"use client";

import { motion } from "framer-motion";
import { useTotalAssets } from "@/hooks/useAssets";

const STATS = [
  { label: "CHAIN",     getValue: () => "RITUAL TESTNET" },
  { label: "AI MODEL",  getValue: () => "GLM-4.7-FP8 · TEE" },
  { label: "PRECOMPILE",getValue: () => "0x0802 · LLM" },
];

export function Hero() {
  const total = useTotalAssets();

  return (
    <section className="relative min-h-[60vh] flex flex-col justify-center overflow-hidden">
      {/* Background grid */}
      <div
        className="absolute inset-0 opacity-[0.03]"
        style={{
          backgroundImage:
            "linear-gradient(rgba(201,168,76,1) 1px, transparent 1px), linear-gradient(90deg, rgba(201,168,76,1) 1px, transparent 1px)",
          backgroundSize: "60px 60px",
        }}
      />

      {/* Scan line */}
      <div className="scan-overlay" />

      {/* Diagonal accent line */}
      <div
        className="absolute top-0 right-0 w-px h-full opacity-10"
        style={{ background: "linear-gradient(180deg, transparent, #C9A84C, transparent)" }}
      />

      {/* Content */}
      <div className="relative z-10 max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0  }}
          transition={{ duration: 0.6, delay: 0.1 }}
        >
          <div className="flex items-center gap-3 mb-6">
            <div className="h-px w-12 bg-gold opacity-60" />
            <span className="font-mono text-[10px] tracking-[0.35em] text-gold uppercase">
              Ritual Chain · Onchain AI Valuation
            </span>
          </div>

          <h1 className="font-display text-6xl md:text-8xl font-light text-platinum leading-[0.9] tracking-tight mb-4">
            Real World<br />
            <span className="text-gold-shimmer italic">Assets.</span><br />
            <span className="text-mist text-4xl md:text-6xl font-light">Verified by AI.</span>
          </h1>

          <p className="text-mist text-base md:text-lg font-body leading-relaxed max-w-xl mt-6 font-light">
            Submit any tangible asset — property, land, art, vehicle — and receive a
            TEE-attested valuation generated by Ritual Chain's native LLM precompile.
            Fractional ownership minted onchain in a single transaction.
          </p>
        </motion.div>

        {/* Stats row */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0  }}
          transition={{ duration: 0.6, delay: 0.35 }}
          className="flex flex-wrap gap-6 mt-10"
        >
          <StatPill label="ASSETS TOKENIZED" value={total.toString()} />
          {STATS.map(s => (
            <StatPill key={s.label} label={s.label} value={s.getValue()} mono />
          ))}
        </motion.div>
      </div>

      {/* Corner decoration */}
      <div className="absolute bottom-8 right-0 w-32 h-32 opacity-5">
        <div className="absolute inset-0 border border-gold" style={{ transform: "rotate(45deg)" }} />
        <div className="absolute inset-4 border border-gold" style={{ transform: "rotate(45deg)" }} />
        <div className="absolute inset-8 border border-gold" style={{ transform: "rotate(45deg)" }} />
      </div>
    </section>
  );
}

function StatPill({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="border border-border px-4 py-2 bg-vault/60">
      <div className="font-mono text-[9px] tracking-[0.25em] text-border uppercase mb-1">{label}</div>
      <div className={`text-sm ${mono ? "font-mono text-mist" : "font-display text-gold text-base"}`}>
        {value}
      </div>
    </div>
  );
}
